pod 'AFNetworking'
pod 'SDWebImage'
pod 'MJExtension'
pod 'MJRefresh'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.3'
pod 'Masonry'
pod 'MWPhotoBrowser'
pod 'FDFullscreenPopGesture'
pod 'MBProgressHUD'
pod 'Bugtags'